<?php
return [
    'host' => 'localhost',
    'port' => '8123',
    'db' => 'default',
    'username' => 'default',
    'password' => '',
    'tablename' => "MeteostationsData",
    'fields' => array(
        "meteostationID",
        "timestamp",
        "temperature",
        "pressure",
        "humidity",
        "wind_max_ms",
        "wind_min_ms",
        "wind_avg_ms",
        "wind_direction",
        "date"
    )
];


